### ISSUE TITLE
Great work!

### ISSUE THREAD

**Issue by robertzk** [gaborcsardi/disposables#1]
Mind if I re-export these functions via [testthatsomemore](https://github.com/robertzk/testthatsomemore)? I would add you as a contributor.

**Comment by gaborcsardi** [comment]
Thanks! Sure, no problem, so don't have to ask me, actually.

**Comment by robertzk** [comment]
Thanks! https://github.com/robertzk/testthatsomemore/pull/10

On Sat, Apr 18, 2015 at 4:21 PM, Gábor Csárdi notifications@github.com
wrote:

> Thanks! Sure, no problem, so don't have to ask me, actually.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/gaborcsardi/disposables/issues/1#issuecomment-94201961
> .

## 

-Robert Krzyzanowski
